name: tips

on:
  push:
  schedule:
    - cron: '0 3 * * 0' #UTC

jobs:
  tips:
    name: tips
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: 8.3
          extensions: mbstring
          coverage: none
      - name: Install Composer dependencies
        run: composer install --no-dev --no-progress --optimize-autoloader
      - name: env
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Run chat:tips
        run: php artisan chat:tips
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DISCORD_CHANNEL: ${{ secrets.DISCORD_CHANNEL }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          NOSTR_SK: ${{ secrets.NOSTR_SK }}
          NOSTR_API_BASE: ${{ secrets.NOSTR_API_BASE }}
